// 2
export const ALL_PRODUCTS_REQUEST = "ALL_PRODUCTS_REQUEST";
export const ALL_PRODUCTS_SUCESS = "ALL_PRODUCTS_SUCESS";
export const ALL_PRODUCTS_FAIL = "ALL_PRODUCTS_FAIL";
export const CLEAR_ERRORS = "CLEAR_ERRORS";


// Get Product Details constant
export const PRODUCT_DETAILS_REQUEST = "PRODUCT_DETAILS_REQUEST";
export const PRODUCT_DETAILS_SUCESS = "PRODUCT_DETAILS_SUCESS";
export const PRODUCT_DETAILS_FAIL = "PRODUCT_DETAILS_FAIL";



